blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Docs
    url: https://github.com/helmut-hoffer-von-ankershoffen/vercel-deploy#-usage
    about: Checkout the documentation.
  - name: ğŸš€ Feature Request
    url: https://github.com/helmut-hoffer-von-ankershoffen/vercel-deploy/discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/helmut-hoffer-von-ankershoffen/vercel-deploy/discussions/new?category=q-a
    about: Ask the community for help
